### ISSUE TITLE
Something wrong with wasm to wat conversion.

### ISSUE THREAD

**Issue by Yeeyooo** [web-devkits/Wasmnizer-ts#164]
Hello, I encountered a problem when I wanted to run some samples according to the given instructions.
Firstly, I picked up the file in the `tests/samples/module-case/export_normal.ts`, which has a function called add.
By using the instruction in "Build ts source code": 
`node cli/ts2wasm.js --opt=3 <source> -o out.wasm`
I got the out.wasm file. Then I want to convert out.wasm to out.wat by using wasm2wat with:
`wasm2wat out.wasm -o out.wat`, which failed, saying:
`000000c: error: unexpected type form(got 0x5e).
Then I use the option --enable-all in wasm2wat, which also failed:
`000000d: error: expected valid field type (got -0x8)`. 
I have no idea what is going on. I'm looking forward to someone's help:)

**Comment by mathisi** [comment]
Hi @Yeeyooo! I noticed that you closed the issue on your own, and I was curious to find out what solution you arrived at, as I am encountering the same error during the conversion process. Kind regards
